matrix:
  include:
      #- sudo: required
      #  language: python
      #  os: linux
      #  services:
      #  - docker
      #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64 PYTHON_FLAVOR=cp27-cp27mu
      #- sudo: required
      #  language: python
      #  os: linux
      #  services:
      #  - docker
      #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64 PYTHON_FLAVOR=cp27-cp27m
      #- sudo: required
      #  language: python
      #  os: linux
      #  services:
      #  - docker
      #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64 PYTHON_FLAVOR=cp36-cp36m
      #- sudo: required
      #  language: python
      #  os: linux
      #  services:
      #  - docker
      #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64 PYTHON_FLAVOR=cp37-cp37m
      #- sudo: required
      #  language: python
      #  os: linux
      #  services:
      #  - docker
      #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686 PYTHON_FLAVOR=cp27-cp27mu
      #- sudo: required
      #  language: python
      #  os: linux
      #  services:
      #  - docker
      #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686 PYTHON_FLAVOR=cp27-cp27m
      #- sudo: required
      #  language: python
      #  os: linux
      #  services:
      #  - docker
      #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686 PYTHON_FLAVOR=cp36-cp36m
      #- sudo: required
      #  language: python
      #  os: linux
      #  services:
      #  - docker
      #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686 PYTHON_FLAVOR=cp37-cp37m
      #- sudo: required
      #  language: python
      #  os: linux
      #  services:
      #  - docker
      #  env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64
      - os: osx
        language: generic
        env: PYTHON=python2
      - os: osx
        language: generic
        env: PYTHON=python3
      - os: osx
        language: generic
        env: PYTHON=python3
        before_install:
            - brew update
            - brew install python@3

install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker pull $DOCKER_IMAGE; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then $PYTHON -m pip install wheel; fi

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh ${PYTHON_FLAVOR} ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then $PYTHON -m pip wheel $PWD -w $PWD/wheelhouse/ && $PYTHON -m pip install pythran-openblas --no-index -f $PWD/wheelhouse; fi
    - ls wheelhouse/

deploy:
  provider: releases
  api_key:
    secure: "oEJ10msw+O9stw08MzxXEiOVy4NByH5J/F0me070QPeis6m+/wWDs+nAIo+BdNwNz5pW7bLAqvdxrj6PhGeuROAr2mtoidWbGdKkU4+a8x/yVpKtb4fvDwRHmA7bDXRsCXCvN6J5QbK0snjQzknsXzYbGau2F4yMfn0ABjW63sPfsOh4swsM5ntE7QWaDp7p+jpGC3mOMOAKUR0JT0Oakp0XDUj3bZv2m24wZn9o+leBpyuJ72U9URihQ7NKVZ4kP075qcp1eapQ1Uy45jKEh3wNDnUCWaP2AeDiHgK/PWN77QK/hK7Djfyqf0ezLH8zzav0cE/GrLHVYPKdoknS8p3pMXafZ7zzJ9ADQCf9xGc1dRlAxHGY7/RlDJ4nZ7TKXBbDeFVn7cfcrDpUNNb1FxJEB0fXxz8UCcTAPZSmpQswLtwB67n1M3ujQXrCX8DJ3l3EFKCp6sgHj2nsGE/8gc1/7Pqw70NbJ4hT+oFu2I3kpzrOenVaMgrJFBtW7XnCTt3yxl3WE8jCItYE4EYT8rSTr35WHycF4V1m7QVQbGuhpLqvLLbjiy0m8jlFoCetQxeOlpCpkzowxJ+d1ul0Au82DHf8F3ZSYgUKCC+hVq/wHUfBGvKfdiwFSiXtt6y56e72R39NSTOYcGOgi3sPVRoWf3ZaQP46XsATWfc70Tk="
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file: wheelhouse/*
  on:
      all_branches: true
